- name: Delete registry_http_secret file if it exists
  delegate_to: localhost
  file:
    state: absent
    path: "/tmp/registry_http_secret"

- name: Fetch registry_http_secret files if it exists
  fetch:
    fail_on_missing: no
    flat: yes
    src: "{{ registryConfigLocation }}/registry_http_secret"
    dest: "/tmp/registry_http_secret"

- name: Set fact for registryHttpSecret
  set_fact:
    registryHttpSecret: "{{ lookup('password', '/tmp/registry_http_secret chars=ascii_letters,digits') }}"

- name: Copy registry_http_secret file to remote
  copy:
    src: "/tmp/registry_http_secret"
    dest: "{{ registryConfigLocation }}/registry_http_secret"

- name: Delete registry_http_secret file
  delegate_to: localhost
  file:
    state: absent
    path: "/tmp/registry_http_secret"